### ISSUE TITLE
Is This Still Working

### ISSUE THREAD

**Issue by NeoxCIA** [lhaasper/fortnite_autoupdate#1]
Is This Still Working?

**Comment by lhaasper** [comment]
nope, sadly not.. i could revive it tho i guess...

**Comment by NeoxCIA** [comment]
Not sure probably would feed the maven poopers even more

**Comment by lhaasper** [comment]
ik 🤣 but finding offsets is annoying as hell for all real coders... u got discord?

**Comment by NeoxCIA** [comment]
Neox#1337

**Comment by lhaasper** [comment]
Ur friend reqs are off, add me: xy0#0001/xy0#1337

**Comment by NeoxCIA** [comment]
Done

**Comment by lhaasper** [comment]
nice
